### PR TITLE
Makes commit link clickable

### PR DESCRIPTION
**Pull request by seemethere**
Signed-off-by: Eli Uriegas <eli.uriegas@docker.com>

### CODE REVIEW

**Review by corbin-coleman — CHANGES_REQUESTED** [review]
BOOOOO

**Review by jose-bigio — CHANGES_REQUESTED** [review]
Don't think it'll work with the exclamation point on the end.

**Review by andrewhsu — APPROVED** [review]
this will solve world hunger

**Review by corbin-coleman — APPROVED** [review]
Sorry. I was wrong.

**Review by andrewhsu — CHANGES_REQUESTED** [review]
i changed my mind...exclamation points give me brain aneurysm

**Review by andrewhsu — APPROVED** [review]
good news: punctuations are back in fashion

**Review by jose-bigio — APPROVED** [review]
LGTM

**Review by andrewhsu — APPROVED** [review]
approved

**Review by corbin-coleman — APPROVED** [review]

**Pull request merged**
